### ISSUE TITLE
Quikflare(pro)'s appearing in weapons endpoint

### ISSUE THREAD

**Issue by kingultron99** [StarCitizenWiki/API#110]
All the different models of quickflare are being returned in the list of weapons from the `/weapons` endpoint.
![firefox_0LlCPv2Srz](https://github.com/StarCitizenWiki/API/assets/43083934/2d0c2bd9-af62-4153-a869-dcde3afa86c9)

**Comment by octfx** [comment]
That is somewhat "correct".  
The `/weapons` endpoint filters items on `type=WeaponPersonal`, which all QuikFlares are placed into.  

That's why the Multi-Tool and ParaMed can also be found there.

I can alternatively add further filters on the `sub_type`:
- Knife
- Large (Scourge Railgun etc.)
- Medium (FS-9 LMG etc.)
- Small (Pistols)
- Grenade (MK-4 _and_ some QuikFlares)
- Gadget (Multi-Tool _and_ some QuikFlares)

Or if only the QuikFlares should be filtered out, I could do that using their class name

**Comment by octfx** [comment]
Feel free to re-open for further discussion :)
